version: '3.3'
services:
  db:
     # TODO db schema not initialised
     image: mysql:5.7
     volumes:
       - /opt/test:/var/lib/mysql
       - ./mysql-dump:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: test
       MYSQL_DATABASE: test_db
       MYSQL_USER: test_user
       MYSQL_PASSWORD: test
     ports:
       - 3306:3306
  web:
      depends_on:
        - db
      image: tomcat:jdk15-openjdk
      volumes:
        - ./imiger-core/target/:/usr/local/tomcat/webapps/
      ports:
        - '8082:8080'
      environment:
        MYSQL_ROOT_PASSWORD: test
        MYSQL_DATABASE: test_db
        MYSQL_USER: test_user 
        MYSQL_PASSWORD: test

